INSERT INTO Notes VALUES (1,1,10); 
INSERT INTO Notes VALUES (2,1,10); 
INSERT INTO Notes VALUES (1,2,10); 
INSERT INTO Notes VALUES (3,1,4); 
INSERT INTO Notes VALUES (3,2,3); 
INSERT INTO Notes VALUES (2,2,3); 