INSERT INTO public.libro (isbn, titulo, editorial, año_publicacion) VALUES (1, 'El señor de los anillos', 'Editorial La Vega', 2010);
INSERT INTO public.libro (isbn, titulo, editorial, año_publicacion) VALUES (2, 'Salamina', 'Booklet', 2018);
INSERT INTO public.libro (isbn, titulo, editorial, año_publicacion) VALUES (3, 'Working Ontologist', 'Springer', 2017);
INSERT INTO public.libro (isbn, titulo, editorial, año_publicacion) VALUES (4, 'SPARQL', 'Springer', 2015);
INSERT INTO public.libro (isbn, titulo, editorial, año_publicacion) VALUES (5, 'Asi hablo zaratrusta', 'Editorial Madrid', 2001);
INSERT INTO public.libro (isbn, titulo, editorial, año_publicacion) VALUES (6, 'Zun-Tzu', 'Editorial dos torres', 2014);
INSERT INTO public.libro (isbn, titulo, editorial, año_publicacion) VALUES (7, 'Cuentos tradicionales', 'Editorial Madrid', 2016);
INSERT INTO public.libro (isbn, titulo, editorial, año_publicacion) VALUES (8, 'Historia y arte', 'Editorial La vega', 2014);
INSERT INTO public.libro (isbn, titulo, editorial, año_publicacion) VALUES (9, 'Poesia Revolucionaria', 'Booklet', 2003);
INSERT INTO public.libro (isbn, titulo, editorial, año_publicacion) VALUES (10, 'Marinero en tierra', 'Editorial Madrid', 1924);
INSERT INTO public.libro (isbn, titulo, editorial, año_publicacion) VALUES (11, 'Sobre los angeles', 'Editorial Barcelona', 1929);
INSERT INTO public.libro (isbn, titulo, editorial, año_publicacion) VALUES (12, 'El sueño de las tortugas', 'Editorial Madrid', 2019);
